application/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from .models import User
from .database import db
from .views import *

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    elif request.method == "POST":
        name = request.form.get("name")
        password = request.form.get("password")
        user = User.query.filter_by(name=name).first()
        if user:
            if password == user.password:
                login_user(user, remember=True)
                return redirect(url_for("views.index"))
            else:
                login_user(user, remember=True)
                return redirect(url_for("views.index"))
        else:
            new_user = User(name=name, password=password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for("views.index"))


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have been logged out from the application", category="success")
    return redirect(url_for("auth.login"))

application/views.py
from sqlite3 import Timestamp
from flask import Blueprint, Flask, redirect, request, url_for, flash
from flask import render_template
from flask import current_app as app
from .models import User, Tracker, Log
from .database import db
from flask_login import current_user, login_required, login_user
import datetime
import matplotlib.pyplot as plt
import os

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
@login_required
def index():
    print(current_user)
    tracker = Tracker.query.all()
    return render_template("tracker_home.html", user=current_user, trackers=tracker)


@views.route("/add-tracker", methods=["GET", "POST"])
@login_required
def add_tracker():
    if request.method == "GET":
        return render_template("add_tracker.html", user=current_user)
    elif request.method == "POST":
        name = request.form.get("name")
        description = request.form.get("description")
        tracker_type = request.form.get("type")
        settings = request.form.get("settings")
        current_user_id = current_user.id
        tracker = Tracker.query.filter_by(name=name).first()
        if tracker and current_user_id == tracker.user_id:
            flash(
                'The tracker "' + name + '" is already added by you.', category="error"
            )
            return redirect(url_for("views.index"))
        else:
            new_tracker = Tracker(
                name=name,
                description=description,
                tracker_type=tracker_type,
                setting=settings,
                user_id=current_user_id,
            )
            db.session.add(new_tracker)
            db.session.commit()
            flash("New tracker successfully added.", category="success")
            return redirect(url_for("views.index"))


@views.route("/edit-tracker/<int:record_id>", methods=["GET", "POST"])
@login_required
def edit_tracker(record_id):
    from .models import Tracker

    this_tracker = Tracker.query.get(record_id)
    this_tracker_name = this_tracker.name
    try:
        if request.method == "POST":
            name = request.form.get("name")
            description = request.form.get("description")
            tracker_type = this_tracker.tracker_type
            settings = request.form.get("settings")

            current_user_id = current_user.id
            tracker = Tracker.query.filter_by(name=name).first()
            if (
                tracker
                and tracker.user_id == current_user_id
                and this_tracker_name != name
            ):
                flash(
                    'The tracker "'
                    + name
                    + '" is already added by you, Try a new name for your tracker.',
                    category="error",
                )
            else:
                from . import db

                this_tracker.name = name
                this_tracker.description = description
                this_tracker.tracker_type = tracker_type
                this_tracker.setting = settings
                db.session.commit()
                flash("Tracker Updated Successfully.", category="success")
                return redirect(url_for("views.index"))
    except Exception as e:
        print(e)
        flash("Something went wrong.", category="error")
    return render_template("edit_tracker.html", user=current_user, tracker=this_tracker)


@views.route("/delete-tracker/<int:record_id>", methods=["GET", "POST"])
@login_required
def delete_tracker(record_id):
    try:
        Tracker_details = Tracker.query.get(record_id)
        Tracker_name = Tracker_details.name
        db.session.delete(Tracker_details)
        db.session.commit()
        flash(Tracker_name + " Tracker Removed Successfully.", category="success")
    except Exception as e:
        print(e)
        flash("Something went wrong.", category="error")
    return redirect(url_for("views.index"))


@views.route("/add-log/<int:record_id>", methods=["GET", "POST"])
@login_required
def add_log(record_id):
    this_tracker = Tracker.query.get(record_id)
    from datetime import datetime

    now = datetime.now()
    try:
        if request.method == "POST":
            when = request.form.get("date")
            value = request.form.get("value")
            notes = request.form.get("notes")

            new_log = Log(
                timestamp=when,
                value=value,
                notes=notes,
                tracker_id=record_id,
                user_id=current_user.id,
                added_date_time=now,
            )
            db.session.add(new_log)
            db.session.commit()
            flash(
                "New log added for " + this_tracker.name + " Tracker",
                category="success",
            )
            return redirect(url_for("views.index"))
    except Exception as e:
        print(e)
        flash("Something went wrong!", category="error")
    return render_template(
        "add_log.html", user=current_user, tracker=this_tracker, now=now
    )


@views.route("/view-tracker-logs/<int:record_id>", methods=["GET", "POST"])
@login_required
def view_tracker_logs(record_id):
    from datetime import datetime

    now = datetime.now()
    cur_tracker = Tracker.query.get(record_id)
    logs = Log.query.all()
    try:
        import sqlite3

        basedir = os.path.abspath(os.path.dirname(__file__))
        SQLITE_DB_DIR = os.path.join(basedir, "../db_directory")
        SQLALCHEMY_DATABASE_URI = "sqlite:///" + os.path.join(
            SQLITE_DB_DIR, "project.sqlite3"
        )
        conn = sqlite3.connect(os.path.join(SQLITE_DB_DIR, "project.sqlite3"))
        print("Database connected..!!")
        cur = conn.cursor()
        cur.execute(
            "select timestamp,value from log where user_id={} and tracker_id={}".format(
                current_user.id, cur_tracker.id
            )
        )
        data = cur.fetchall()
        print(data)
        dates = []
        values = []
        from dateutil import parser

        for row in data:
            dates.append(parser.parse(row[0]))
            values.append(row[1])
        # dates.sort()
        from matplotlib import style, set_color

        style.use("fivethirtyeight")
        fig = plt.figure(figsize=(18, 8))
        plt.plot_date(dates, values, "-", color="black")
        plt.xlabel("Date and Time")
        plt.ylabel("Values")
        # plt.set_color("black")
        plt.tight_layout()
        plt.savefig("./static/images/graph.png")

        cur.close()
        conn.close()

        return render_template(
            "tracker_logs.html", user=current_user, tracker=cur_tracker, logs=logs
        )
    except Exception as e:
        print(e)
        flash("Something Went Wrong.", category="error")
        return render_template(
            "tracker_logs.html", user=current_user, tracker=cur_tracker, logs=logs
        )


@views.route("/edit-log/<int:record_id>", methods=["GET", "POST"])
@login_required
def edit_log(record_id):
    this_log = Log.query.get(record_id)
    this_tracker = Tracker.query.get(this_log.tracker_id)
    try:
        if request.method == "POST":
            when = request.form.get("date")
            value = request.form.get("value")
            notes = request.form.get("notes")

            this_log.timestamp = when
            this_log.value = value
            this_log.notes = notes

            db.session.commit()
            flash(this_tracker.name + "Log Updated Successfully.", category="success")
            return redirect(
                url_for("views.view_tracker_logs", record_id=this_log.tracker_id)
            )
    except Exception as e:
        print(e)
        flash("Something went wrong.", category="error")
    return render_template(
        "edit_log.html", user=current_user, tracker=this_tracker, log=this_log
    )


@views.route("/delete-log/<int:record_id>", methods=["GET", "POST"])
@login_required
def delete_log(record_id):
    log_details = Log.query.get(record_id)
    tracker_id = log_details.tracker_id
    try:
        db.session.delete(log_details)
        db.session.commit()
        flash("Log deleted Successfully.", category="success")
    except Exception as e:
        print(e)
        flash("Something went wrong.", category="error")
    return redirect(url_for("views.view_tracker_logs", record_id=tracker_id))

templates/add_log.html
{% extends "base.html" %}
{% block title %}Add Log{% endblock %}

{% block body %} 
    <form method="post">
        <h3 align="center"></h3>
        <div class="form-group">
            <h2>Log {{ tracker.name }}</h2>
            <br>
            <div align="center">
                <label for="date">When: </label>
                <input type="datetime-local" class="form-control" id="date" name="date" value="{{ now }}"  required />
                <label for="value">Value: </label><br>
                
                {% if tracker.tracker_type == 'Numerical' %}
                    <input type="number" id="value" name="value" placeholder="Enter number: " maxlength="30" required />
                {% endif %}

                {% if tracker.tracker_type == "Multiple Choice" %}
                    <select id="value" class="form-control" name="value" required>
                        {% set options = tracker.setting.split(",") %}
                        {% for setting in options %}
                        <option value="{{ setting }}">{{setting}}</option>
                        {% endfor %}
                    </select>
                {% endif %}
    
                {% if tracker.tracker_type == "Temperature" %}
                <input type="range" class="form-range" id="value" name="value" placeholder="Enter Temperature: " min="0" max="50" oninput="this.nextElementSibling.value = this.value"  maxlength="30" required />
                <output>25</output>
                {% endif %}
                <br>
                </tr>
                <label for="notes">Notes: </label>
                <textarea class="form-control" id="notes" name="notes" placeholder="Enter notes" maxlength="200"></textarea>
                <br>
                <button type="submit" class="btn btn-dark text-light">Add Log</a>
            </div>
        </div>
    </form>
{% endblock %}

templates/add_tracker.html
{% extends "base.html" %}
{% block title %}Add Tracker{% endblock %}

{% block body %}
<form method="post" class="">
    <div class="form-group">
        <h2>Add Tracker</h2>
        <br>
        <div align="center">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter tracker name" maxlength="30" required />

            <label for="type">Tracker Type</label>
            <select id="type" class="form-control" name="type" required>
                <option value="Numerical">Numerical</option>
                <option value="Multiple Choice">Multiple Choice</option>
                <option value="Temperature">Temperature</option>
            </select>

            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" placeholder="Enter tracker description" maxlength="200"></textarea>

            <label for="settings">Additional settings</label>
            <textarea class="form-control" id="settings" name="settings" placeholder="Enter tracker settings" maxlength="200"></textarea>

            <br>

            <button type="submit" class="btn btn-dark text-light">Add Tracker</button>
        </div>
    </div>
</form>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content = "width=device-width,initial-scale=1"
        
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        {% block style %}
        {% endblock %}
        <title>{% block title %}Home{% endblock %}</title>
        <style>
          .main-content {
            height: calc(100vh - 115px);
            display: flex;
            flex-direction: column;
            /* justify-content: center; */
            align-items: center;
            overflow-y: auto;
            margin-bottom: 20px;
            padding: 20px;
          }
          .app-contanier {
            position: relative;
            max-height: 100vh;
            overflow: hidden;
          }
          .app-header {
            position: sticky;
            top: 0;
          }
          .app-footer {
            position: sticky;
            bottom: 0px;
          }

          .bg-dark {
            background-color: black !important;
          }
        </style>
    </head>

    <body>


<div class="container vh-100 app-contanier"> 
  {% if user %}
  <nav class="navbar navbar-expand-lg navbar-light bg-dark p-3 app-header">
  <div class="d-flex align-items-center justify-content-end w-100 text-light">
    <button class="btn btn-dark-outline mx-3 my-sm-0" type="submit">
      <a class="text-light" href="{{ url_for('views.index') }}">
      <!-- <span> -->
      Hello {{ user.name }}
      <!-- </span>  -->
      </a>
    </button>
    <button class="btn btn-dark-outline mx-3 my-sm-0" type="submit">
        <a class="text-light" href="{{ url_for('auth.logout') }}">
            Logout
        </a>
    </button>
  </div>
</nav>
{% else %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="d-flex align-items-center justify-content-end w-100 text-light">
    <span>
      Login
    </span> 
  </div>
</nav>
{% endif %}
<div class="main-content">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}
  {% block body %} 
  {% endblock %}
</div>
<div class="bg-dark p-3 app-footer">
  <!-- Copyright -->
  <div class="text-light mb-3 mb-md-0">
      Copyright © 2022. All rights reserved.
  </div>

</div>
</div>
        
    </body>
</html>

templates/edit_log.html
{% extends "base.html" %}
{% block title %}Edit Log{% endblock %}

{% block body %} 
    <form method="post">
        <h3 align="center"></h3>
        <div class="form-group">
            <h2>Edit Log {{ tracker.name }}</h2>
            <br>
            <div align="center">
                <label for="date">When: </label>
                <input type="datetime-local" class="form-control" id="date" name="date" value="{{ log.timestamp }}" required />
                
                <label for="value">Value: </label>

                {% if tracker.tracker_type == "Numerical" %}
                    <input type="number" class="form-control" id="value" name="value" placeholder="Enter number: " maxlength="30" value="{{ log.value }}" required />
                {% endif %}

                {% if tracker.tracker_type == "Multiple Choice" %}
                    <select id="value" class="form-control" name="value" required>
                        {% set options = tracker.setting.split(",") %}
                        {% for setting in options %}
                        <option value="{{ setting }}">{{setting}}</option>
                        {% endfor %}
                    </select>    
                {% endif %}

                {% if tracker.tracker_type == "Temperature" %}
                <input type="range" class="form-range" id="value" name="value" placeholder="Enter Temperature: " min="0" max="50" maxlength="30" value="{{ log.value }}"  required />
                {% endif %} 

                <label for="notes">Notes: </label>
                <textarea class="form-control" id="notes" name="notes" placeholder="Enter notes" maxlength="200">{{ log.notes }}</textarea>
                <br>
                <button class="btn btn-dark text-light" type="submit">Update Log</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/edit_tracker.html
{% extends "base.html" %}
{% block title %}Edit Tracker{% endblock %}

{% block body %}

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">
        <h2>Edit Tracker</h2>
        <br>
        <div align="center">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter tracker name" maxlength="30" value="{{ tracker.name }}" required />

            <label for="type">Tracker Type</label>
            <select id="type" class="form-control" name="type" required disabled>
                <option value="{{ tracker.tracker_type }}">{{ tracker.tracker_type }}</option>
                <option value="Numerical">Numerical</option>
                <option value="Multiple Choice">Multiple Choice</option>
                <option value="Temperature">Temperature</option>
            </select>

            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" placeholder="Enter tracker description" maxlength="200">{{ tracker.description }}</textarea>

            <label for="settings">Additional settings</label>
            <input type="text" class="form-control" id="settings" name="settings" placeholder="Enter any additional settting is you want" maxlength="80" value="{{ tracker.setting }}" />
            
            <br>

            <button type="submit" class="btn btn-dark text-light">Update Tracker</button>
        </div>
    </div>
</form>



{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block style %}

<style>
.login-section {
    display: flex;  
    align-items: center;
    height: 100%;
    margin: 0;
    max-height: 100;
}
</style>

{% endblock %}

{% block title %} Login Page {% endblock %}
{% block body %}
    <h1 class=".font-weight-bold">Quantified Self App</h1> 
    <section class="login-section">
        <div class="col-12 m-auto">
            <div class="d-flex justify-content-center align-items-center">
                <div class="col-6">
                    <img width="80%" src="../static/images/tracker-logo.png" class="img-fluid" alt="App Main Image">
                </div>
                <div class="col-6">
                    <form method="post">
                        <!-- Name Input -->
                        <div class="form-outline mb-3">
                            <label class="form-label" for="form3Example3">Name</label>
                            <input type="text" name="name" id="form3Example3" class="form-control" placeholder="Enter your name"/>
                        </div>
                        <!-- Password Input -->
                        <div class="form-outline mb-3">
                            <label class="form-label">Password</label>
                            <input type="password" name="password"  class="form-control" placeholder="Enter your password"/>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="w-100 btn btn-dark" value="Submit Form">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/tracker_home.html
{% extends "base.html" %}
{% block title %}Dashboard {% endblock %}

{% block body %}

<div class="w-100">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Tracker</th>
                <th scope="col">Description</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>

        <tbody>
            {% for tracker in trackers %}
            {% if tracker.user_id == user.id %}
                <tr>
                    {% set tracker_id=tracker.id %}
                    <td><a href="{{ url_for('views.view_tracker_logs',record_id=tracker_id) }}">{{ tracker.name  }}</a></td>
                    <td>{{ tracker.description  }}</td>
                    <td><a href="{{ url_for('views.add_log',record_id=tracker_id) }}" class="btn">Add log</a></td>
                    <td>
                        <button class="btn btn-dark">
                        <a class="text-light" href="{{ url_for('views.edit_tracker',record_id=tracker_id) }}">Edit Tracker</a>
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-dark">
                        <a class="text-light" href="{{ url_for('views.delete_tracker',record_id=tracker_id) }}">Delete Tracker</a>
                        </button>
                    </td>
                </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div align="center">
        <a href="/add-tracker" class="btn btn-dark">Add Tracker</a>
    </div>
</div>

{% endblock %}

templates/tracker_logs.html
{% extends "base.html" %}
{% block title %}View Tracker Logs{% endblock %}

{% block body %}

<div class="container emp-profile shadow-lg">
    <form method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="profile-head">
                    <h2><strong>{{ tracker.name }}  Tracker</strong></h2>

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" role="tab" aria-controls="home" aria-selected="true">Graph</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <img class="img-fluid mx-auto d-block" src="{{ url_for('static',filename='../static/images/graph.png') }}" alt="Trends">
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <ul class="nav nav-tabs" id="myTab2" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab2" data-toggle="tab" role="tab" aria-controls="home" aria-selected="true">Logs</a>
            </li>
        </ul>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">On</th>
                    <th scope="col">Value</th>
                    <th scope="col">Notes</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                {% if log.user_id==user.id and log.tracker_id==tracker.id %}
                    <tr>
                        {% set log_id=log.id %}
                        <td>{{ log.timestamp }}</td>
                        <td>{{ log.value }}</td>
                        <td>{{ log.notes }}</td>
                        <td>
                            <a href="{{ url_for('views.edit_log',record_id=log_id) }}">Edit Log</a>
                        </td>
                        <td>
                            <a href="{{ url_for('views.delete_log',record_id=log_id) }}">Delete Log</a>
                        </td>
                    </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>

        {% set tracker_id=tracker.id %}
        <div align="center">
            <button class="btn btn-dark">
                <a class="text-light" href="{{ url_for('views.add_log' , record_id = tracker_id) }}">Add New Log</a>
            </button>
        </div>
    </form>
</div>
{% endblock %}